# Generated by Django 3.1.3 on 2020-11-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201125_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbtfile',
            name='video_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='NBTImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('nbt_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nbtfile')),
            ],
        ),
    ]
